### ISSUE TITLE
Use FileSystemWatcher instead of VS file save events

### ISSUE THREAD

**Issue by glittle** [madskristensen/BundlerMinifier#105]
When I edit a TypeScript (TS) file, the JS file is updated immediately.

However, the bundle that contains the JS file does not get updated.

If I manually edit that JS file, the bundle does get updated.

This is similar to #86, but while actively editing the files.  

If a FileSystemWatcher is not used, then maybe the Bundler can be told to watch for saves to the TS file, and when it is saved, get the generated JS and update the bundle?  The bundleconfig.json file could simply reference the TS files directly, and bundle the associated JS files.
```
  {
    "outputFileName": "Scripts/SiteBundle.js",
    "inputFiles": [
      "Scripts/site-status.ts",
      "Scripts/Site.ts"
    ]
  },
```

**Comment by RichiCoder1** [comment]
Or at the very least, allow signalling to BundleMinifier that VS save events won't be enough and it should use FileSystemWatcher instead.

**Comment by alandraper** [comment]
I think this would also help with bundling .css which are built from .less files which #include other .less files.

**Comment by madskristensen** [comment]
Please help verify this fix in the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/).

**Comment by madskristensen** [comment]
Can someone please help verify the CI build so I can release a new version?

**Comment by RichiCoder1** [comment]
Just need to verify these steps?:
1) Install Extension
2) Create a bundle where one input is dynamically generated
3) Regenerate the input file
4) verify the bundle has been regenerated

If that's correct, I can do that when I get back from lunch.

**Comment by madskristensen** [comment]
Thanks, much appreciated. Also test out if performance is still good and if it "feels" right too. It was a major change to move to using a `FileSystemWatcher`

**Comment by Bokkeman** [comment]
I’ve been using it (build 1.8.154) for a few days already since I got the notification that you’d made a change that affected those issues.

Not sure how else we should give feedback, so here goes:

During my first session it worked initially (i.e. for a few saves & compiles of .LESS files) but then it seemed to go into a spasm and then refused to be triggered by the save & compile process, and also showed no indication of having done anything if I right-clicked on the bundle file and chose “Update bundles”.

I remember wondering where the output of the Bundler goes – do you generate a log file somewhere? There was literally no response or feedback on selecting “update bundles”.

I then installed the “Enable bundle on build” to somehow get my bundles updated. This worked but of course it’s a poor workflow to have to recompile the whole app to see a change to a bundle .CSS or .JS file.

 

Later I restarted VS2015 and since then it has been working as expected.

 

One small thing: the Bundler&Minifier seems to be competing with the WebCompiler for updates to the status bar. If I now save a .less file which gets compiled and then triggers the compiler, the status bar changes from “Compiling…” to “Bundle updated” to “compiled successfully” which is not the expected final status. This only happens on FIRST save after opening the project. On second and subsequent runs, it correctly transitions from “Compiling…” to “compiled successfully” to “Bundle updated”. Why would it be different the first time?

 

Also, it would be great if you could always pipe the output of the bundler (as well as the compiler) to their respective Output window sections. This might also be useful for troubleshooting error conditions should they occur as in my first experience where the bundler seems to have bombed and become unresponsive.

It is only when I do a project build (with your “Enable bundle on build” enabled) that they seem to pipe their output to the Output / Build window.

 

Hope this helps.

 

Regards,

 

Tian van Heerden

 <http://www.sageonlinetools.co.za/> Sage Online Tools

082 652 7440

 <callto:tianvh> Skype
