### ISSUE TITLE
html minification error

### ISSUE THREAD

**Issue by peymanebrahimi** [madskristensen/BundlerMinifier#134]
### Installed product versions
- Visual Studio: [enterprise 2015]
- This extension: [2.0.235]

### Description
non sense error while minifying html files, which previous versions had no issue.

### Current behavior
in error list window says "expected identifier , found ' '   "
`<div class="modal-header bg-primary">
    <div style="font-size: large">افزودن فروشنده </div>
</div>`

```

**Comment by IlBaffo** [comment]
Same problem for me after updating from 1.9x to 2.x
Additionally it checks out every file it minifies, even if it is not changed.

We have a deploy in production today and I am trying since yersterday to downgrade to 1.9 but it seems impossibile to do.
Chocolatey keeps downloading the latest version even when using the -version switch, if anyone has an URL to 1.9 package please link it here.

**Comment by IlBaffo** [comment]
I have found a workaround to HTML minifications failing.

It appears that what is causing the errors is actually the minification on INLINE CSS ATTRIBUTES, even tough the syntax is valid, by the NUglify library.

Adding "minifyInlineCssCode: false" to the bundleconfig.json for every HTML file prevents that minification, and thus the errors, from happening.
  ```
  {
        "outputFileName": "myfile.html",
        "minify": {
            "enabled": true,
            "minifyInlineCssCode": false
        },
        "inputFiles": [
            "myfile.html"
        ]
    }
```

I am still investigating on why every file gets checked-out from source control but, at least I am able to release my woftware today :)
