### ISSUE TITLE
Automatically Updating .min.css or .min.js files

### ISSUE THREAD

**Issue by moojjoo** [madskristensen/BundlerMinifier#247]
### Installed product versions
- Visual Studio: 2015 Professional and TFS 2012.
- This extension: 2.4.340

### Description
https://github.com/madskristensen/BundlerMinifier/blob/master/README.md#minification
The magnification is not checking out and updating the .min.css or .min.js versions.

### Steps to recreate
1. Open any css or js file and edit
2. The min.css or min.js remains locked in source control

I actually do not need to bundle, just minify.  And the ability to GROUP minifiy CSS and JS in directories to reduce the request/response on our server.   I attempted the bundle technique and it actually slowed the site down.

### Current behavior
It is not updating the minified css or js files.  If you ever ctrl and left click and minifiy name it site.css it does not make a site.min.css

### Expected behavior
1. Should update the .min.css and .min.js files if the .css and .js is updated.
2. If adding multiple .css:  a.css, b.css, c.css shouldn't it makes a NAME.css and Name.min.css?

**Comment by moojjoo** [comment]
Hello?  Is there anybody out there?

**Comment by moojjoo** [comment]
Anybody else having this issue?  Again in my case I do not want to bundle, just minify.  I loved the old version worked everytime.

**Comment by manigandham** [comment]
If you want runtime access similar to the older framework, you can use a library like https://github.com/Shazwazza/Smidge

Not sure what you mean by group files since that's what bundling is. The default bundler/minifier config will take all the files listed as input in `bundleconfig.json`, combine them together and then minify them into 1 output file.

You can automate by using the build hooks with the dotnet cli tooling.

**Comment by dammitjanet** [comment]
This might be the same as #201

**Comment by moojjoo** [comment]
Thank you everyone.
