### ISSUE TITLE
Minifier deletes original source files

### ISSUE THREAD

**Issue by stonecourier** [madskristensen/BundlerMinifier#80]
Using version 1.5.132 and visual studio 2015 community edition Version 14.0.23107.0 D14REL,

The nuget version was 1.5.118 which I then upgraded 10 1.5.132.

When you do a clean and rebuild, quite often it deletes the original source files.

We have disabled the build minification process at this stage and removed the nuget package. I hope you can find a fix.

**Comment by madskristensen** [comment]
Do you have the latest version of the nuget package too?

**Comment by stonecourier** [comment]
I updated nuget to 1.5.132 and the problem still occured.

**Comment by brandonam** [comment]
I've been experiencing this issue with 1.5.132 as well. I lost a week worth of work due to not committing changes to my repo before I went on leave (my own fault) but now my only way to work going forward is to remove bundling.

**Comment by marktaling** [comment]
Same issue occurs here. For me it happens when I only want to minify a file (without the bundling). In that scenario the input and output file are the same, resulting in the input being removed.

In the following example (generated by using the options in the context menu)
```javascript  
[
     {
        "outputFileName": "Scripts/controllers.js",
        "inputFiles": [
          "scripts/controllers/controller1.js",
          "scripts/controllers/controller2.js"
        ]
     },
     {
        "outputFileName": "Scripts/app.js",
        "inputFiles": [
           "Scripts/app.js"
        ]
     }
]
```
The following files are removed:
controllers.js
controllers.min.js
app.js
app.min.js

Afterwards, the bundler breaks because it cannot find the app.js file anymore.
