### ISSUE TITLE
Cooperate with WebCompiler

### ISSUE THREAD

**Issue by brunis** [madskristensen/BundlerMinifier#86]
It's a big problem that i have to rebuild a 66 project solution to get my .less files recompiled and bundles regenerated.
My status bar says compiled succesfully, but .less files are not compiled and obviously even if bundles were regenerated what would be the point?

**Comment by madskristensen** [comment]
Please provide simple repro steps

**Comment by brunis** [comment]
After investigating i think the WebCompiler is the issue, i registered an issue there instead. Webcompiler does not timestamp the file when modified, which probably prevents file notify from working, which is probably a bug in windows. Even if you delete the file, it's recreated with an old timestamp. When that is fixed i'm sure BunderMinifier will kick in and recreate the bundle.

**Comment by alfredoceballosr** [comment]
The issue "vs addon fail #153" on Web compiler extension is pretty important since if the file change time is not updated, other tools like Bundler & Minifier extension that relay on this change will not be triggered.

A very simple scenario to reproduce the issue is to create a SCSS file and compile it into a CSS. Then bundle the resulting CSS file with other style sheets at hand. You'll notice that when you update and save the SCSS file, the compiled CSS works fine and reflects the changes, but the bundled and minified file is never updated.

**Comment by martonx** [comment]
This is a big issue for me too. Please fix it!

**Comment by 304NotModified** [comment]
+1. This is a really important issue IMO.

**Comment by kipusoep** [comment]
Bumped into this issue today and it's really blocking our work :-(
WebCompiler and BundlerMinifier should work as a team IMO.

**Comment by kipusoep** [comment]
So here's a simple demo project: https://kipusoep.stackstorage.com/index.php/s/bu6yscJ9v9OZtjn

Steps to reproduce (with VS2015, WebCompiler and BundlerMinifier installed):
1. Open the solution in VS2015
2. Open \CSS\style.less inside the IDE
3. Change background-color: red; to background-color: blue;
4. Save the file
5. Open \CSS\style.css
6. The change from step 3 is visible (because of WebCompiler)
7. Open \CSS\bundle.css

_Expected behavior:_
8. The change from step 3 is visible (because of WebCompiler __and__ BundlerMinifier)
_Actual behavior:_
8. __The change from step 3 is _not_ visible__ (because of WebCompiler __and__ BundlerMinifier)

**Comment by madskristensen** [comment]
Thanks for the repro

**Comment by madskristensen** [comment]
It has to do with the fact that this extension isn't using a file system watcher, but relies on the file being saved in VS to run the bundler. The reason this has yet to be fixed to use a file system watcher is that when working with Sass and Less, you don't need to use this extension at all. Just use the Web Compiler and create a single .scss/.less files that import the ones that would go in the bundle. It would look like this:

**all.less:**
```less
@import "file1.less";
```

**Comment by kipusoep** [comment]
How about having third party libraries already compiled to CSS?

**Comment by madskristensen** [comment]
@kipusoep You probably want to serve bootstrap from a CDN and not bundled with your custom CSS.

**Comment by 304NotModified** [comment]
And what about typescript and a javascript bundle?

**Comment by kipusoep** [comment]
Seems to me it should still be possible to use both WebCompiler and BundlerMinifier side-by-side.

**Comment by cveld** [comment]
We use WebCompiler to compile a couple of less files into css files and then we use BundlerMinifier to bundle the css files into one minified css. We enabled both add-ins to run on build, but it seems that the bundler is run first, and the compiler afterwards. It should be the other way around. How can we fix this?

**Comment by madskristensen** [comment]
Fixed

**Comment by kipusoep** [comment]
Awesome!

**Comment by 304NotModified** [comment]
:+1:

**Comment by madskristensen** [comment]
Please help verify this fix in the latest [CI build](http://vsixgallery.com/extension/a0ae318b-4f07-4f71-93cb-f21d3f03c6d3/).

**Comment by madskristensen** [comment]
Can someone please help verify the CI build so I can release a new version?
